#!/usr/bin/php
<?php

array_shift($argv);

array_walk($argv, function ($path) {
    if (!is_file($path)) {
        echo sprintf(
            "\033[31mSpecified path %s is not a file\033[0m\n",
            $path,
            json_last_error_msg(),
            json_last_error()
        );
        return;
    }

    $json = file_get_contents($path);
    $decoded = json_decode($json);

    if (json_last_error() !== JSON_ERROR_NONE) {
        echo sprintf(
            "\033[31mFailed to decode %s due to %s (%s)\033[0m\n",
            $path,
            json_last_error_msg(),
            json_last_error()
        );
        return;
    }

    $json = json_encode($decoded, JSON_UNESCAPED_SLASHES | JSON_PRETTY_PRINT);
    file_put_contents($path, $json);

    echo sprintf(
        "\033[32mFixed %s\033[0m\n",
        $path
    );
});
